version: '3'
services:
  web:
    build: .  # Build from Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Sync code changes
    ports:
      - "8000:8000"  # Map port